"""empty message

Revision ID: 405b3bab8362
Revises: 14faa3fd5c59
Create Date: 2020-01-11 21:46:52.930577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405b3bab8362'
down_revision = '14faa3fd5c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'datail2')
    op.drop_column('issues', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('status', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('issues', sa.Column('datail2', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
