"""empty message

Revision ID: 498df7e10791
Revises: 405b3bab8362
Create Date: 2020-01-11 21:47:27.982901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498df7e10791'
down_revision = '405b3bab8362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('detail2', sa.String(length=256), nullable=True))
    op.add_column('issues', sa.Column('status', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'status')
    op.drop_column('issues', 'detail2')
    # ### end Alembic commands ###
